name: ds3030-data-analytics
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - mlxtend
  - wordcloud
  - pywaffle
  - statsmodels
  - jupyter
  - notebook
  - ipykernel
  - pip
  - pip:
      - openpyxl
      - plotly
      - yellowbrick
      - tqdm
      - nltk
      - textblob
      - spacy
